name: CI first pipeline

on:
  push: 
   branches: [ main ]
  
jobs: 
 build: 
  runs-on: ubuntu-latest
  defaults:
    run:
      working-directory: ./first_pipeline
  
  steps:
   - name: Checkout Code
     uses: actions/checkout@v4
   - name: Set up Node.js
     uses: actions/setup-node@v3
     with: 
      node-version: '16'  
      cache: 'npm'
      cache-dependency-path: './package-lock.json'
   - name: Install dependencies
     run: npm install
   - name: Run Tests
     run: npm test
   - name: Run app
     run: npm run run